### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by PaulWoitaschek** [Shilo/SD2-Caffeine-Mod#1] opened 2020-08-27 13:23 UTC
Usually the source code is added to git which does all the versioning for you. That's the reason github is there at all. 
It would be great if you directly add your git repo instead of attached zip folders on releases.

**Comment by caviyacht** [comment] 2020-08-27 19:21
I wouldn't put the source here as it is a decompiled version of the game.

**Comment by Shilo** [comment] 2020-08-28 01:00
@PaulWoitaschek - As @caviyacht pointed out, this is not a good idea to share the source code. I made this repo relatively empty for a reason. I would be happy to share my code changes with public, but the issue is that modding Soda Dungeon 2 requires me to alter the original source code of the game itself, which is a legally gray area already. The developer is OK with modding the game for QoL changes, but by no means does that allow me to make the source code of the game, made public. Thank you for your input though!

I will close this issue and end with: I'm not able to supply source code due to respect and legal reasons for the Soda Dungeon 2 developer.

**Closed as completed by Shilo** 2020-08-28 01:00 UTC
Labels: invalid
